/**
 * Dependency-free PDF generator for ShopTantra seller registration records.
 *
 * Produces a valid, standards-compliant single-page A4 (PDF 1.4) document
 * containing a seller's professional profile. No external PDF library is
 * used, to avoid a risky production dependency change; the writer below
 * tracks exact byte offsets so the cross-reference table is correct and the
 * output opens in any PDF reader.
 */

export interface SellerPdfRecord {
  sellerId: string;
  businessName: string;
  ownerName: string;
  email: string;
  phone: string;
  businessType?: string | null;
  gstNumber?: string | null;
  panNumber?: string | null;
  addressLine?: string | null;
  city?: string | null;
  state?: string | null;
  pincode?: string | null;
  bankAccountHolder?: string | null;
  bankAccountMasked?: string | null;
  bankIfsc?: string | null;
  status: string;
  registeredAt: string;
}

const MARGIN_X = 56;
const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;

function escapeText(s: string): string {
  return String(s ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/[\r\n]+/g, ' ');
}

// Keep the content stream to printable ASCII so offsets stay predictable.
function sanitize(s: unknown): string {
  return String(s ?? '')
    .replace(/[^\x20-\x7E]/g, '')
    .trim();
}

interface Line {
  text: string;
  size: number;
  bold?: boolean;
  gap?: number;
  color?: [number, number, number];
}

function buildContentStream(lines: Line[]): string {
  let y = PAGE_HEIGHT - MARGIN_X;
  const parts: string[] = [];
  for (const line of lines) {
    const size = line.size;
    y -= line.gap ?? 0;
    y -= size + 4;
    if (y < MARGIN_X) break; // single page: stop before overflow
    const [r, g, b] = line.color ?? [0.15, 0.15, 0.15];
    const font = line.bold ? '/F2' : '/F1';
    parts.push(
      `BT ${r} ${g} ${b} rg ${font} ${size} Tf ${MARGIN_X} ${y.toFixed(2)} Td (${escapeText(line.text)}) Tj ET`
    );
  }
  const ruleY = (PAGE_HEIGHT - 96).toFixed(2);
  parts.push(
    `0.92 0.35 0.05 RG 1.2 w ${MARGIN_X} ${ruleY} m ${(PAGE_WIDTH - MARGIN_X).toFixed(2)} ${ruleY} l S`
  );
  return parts.join('\n');
}

export function generateSellerPdf(record: SellerPdfRecord): Buffer {
  const navy: [number, number, number] = [0.106, 0.227, 0.42];
  const orange: [number, number, number] = [0.92, 0.35, 0.05];
  const grey: [number, number, number] = [0.4, 0.4, 0.4];
  const dark: [number, number, number] = [0.15, 0.15, 0.15];

  const lines: Line[] = [];
  lines.push({ text: 'SHOPTANTRA', size: 22, bold: true, gap: 6, color: navy });
  lines.push({ text: 'Seller Registration Record', size: 12, gap: 2, color: grey });
  lines.push({ text: `Seller ID: ${sanitize(record.sellerId)}`, size: 13, bold: true, gap: 16, color: orange });

  const rows: Array<[string, unknown]> = [
    ['Business Name', record.businessName],
    ['Owner Name', record.ownerName],
    ['Business Type', record.businessType],
    ['Email', record.email],
    ['Phone', record.phone],
    ['GST Number', record.gstNumber],
    ['PAN Number', record.panNumber],
    ['Address', record.addressLine],
    ['City', record.city],
    ['State', record.state],
    ['Pincode', record.pincode],
    ['Bank Account Holder', record.bankAccountHolder],
    ['Bank Account', record.bankAccountMasked],
    ['IFSC', record.bankIfsc],
    ['Account Status', record.status],
    ['Registered On', record.registeredAt],
  ];

  lines.push({ text: 'Business Details', size: 14, bold: true, gap: 18, color: navy });
  for (const [label, value] of rows) {
    const v = sanitize(value);
    if (!v) continue;
    lines.push({ text: `${label}: ${v}`, size: 10.5, gap: 6, color: dark });
  }

  lines.push({
    text: 'System-generated by ShopTantra. The Seller ID is permanent and non-editable.',
    size: 8.5,
    gap: 20,
    color: grey,
  });

  const content = buildContentStream(lines);

  const objects: string[] = [];
  objects.push('<< /Type /Catalog /Pages 2 0 R >>');
  objects.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');
  objects.push(
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH.toFixed(2)} ${PAGE_HEIGHT.toFixed(2)}] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>`
  );
  objects.push(`<< /Length ${Buffer.byteLength(content, 'latin1')} >>\nstream\n${content}\nendstream`);
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(Buffer.byteLength(pdf, 'latin1'));
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, 'latin1');
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) {
    xref += `${off.toString().padStart(10, '0')} 00000 n \n`;
  }
  pdf += xref;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'latin1');
}
