import { NextResponse } from 'next/server';
import { Prisma } from '@prisma/client';
import { prisma } from '../../../lib/prisma';
import { classifyDbError } from '../../../lib/authUtils';
import {
  authorizePolyfillRequest,
  body0,
  enforceOwnership,
} from '../../../lib/polyfillAuth';

// Define categories list for static mapping
const STATIC_CATEGORIES = [
  { id: 'cat-1', name: 'Electronics' },
  { id: 'cat-2', name: 'Fashion' },
  { id: 'cat-3', name: 'Home & Kitchen' },
  { id: 'cat-4', name: 'Beauty' },
  { id: 'cat-5', name: 'Grocery' },
  { id: 'cat-6', name: 'Books' },
  { id: 'cat-7', name: 'Toys' },
  { id: 'cat-8', name: 'Sports' },
  { id: 'cat-9', name: 'Automotive' },
  { id: 'cat-10', name: 'Mobile Accessories' },
  { id: 'cat-11', name: 'Furniture' },
  { id: 'cat-12', name: 'Health' },
];

// ---------------------------------------------------------------------------
// Supabase column name → Prisma field name.
//
// The browser speaks the Supabase shape (`created_at`, `user_id`,
// `approval_status`, `monthly_price`, …) while Prisma accepts only its own
// field names. Every incoming column therefore has to be translated before it
// reaches the client, otherwise `.order('created_at')` arrives as
// `orderBy: { created_at: … }`, Prisma answers with a validation error and the
// route returns HTTP 500 — which silently emptied the admin product list, the
// buyer order history / invoices / tickets, the plan list and the vendor store
// page while only the ordered reads looked broken.
//
// The field list below comes from the generated client's DMMF, so it always
// matches the schema that was actually deployed.
// ---------------------------------------------------------------------------
const MODEL_FIELDS: Record<string, Set<string>> = (() => {
  const fields: Record<string, Set<string>> = {};
  try {
    for (const model of Prisma.dmmf.datamodel.models) {
      fields[model.name] = new Set(model.fields.map((field) => field.name));
    }
  } catch {
    console.warn('[supabase-polyfill] Prisma DMMF unavailable; column translation falls back to camelCase only');
  }
  return fields;
})();

/** Which Prisma model backs each polyfill table. */
const TABLE_MODEL: Record<string, string> = {
  profiles: 'User',
  sellers: 'Seller',
  products: 'Product',
  orders: 'Order',
  reviews: 'Review',
  leads: 'Lead',
  subscriptions: 'Subscription',
  subscription_plans: 'SubscriptionPlan',
  support_tickets: 'SupportTicket',
  newsletter_subscriptions: 'NewsletterSubscription',
  contact_inquiries: 'ContactInquiry',
  addresses: 'Address',
};

/**
 * Columns whose Supabase name is not just a snake_case spelling of the Prisma
 * field. Everything else is covered by `snakeToCamel` (`created_at` →
 * `createdAt`, `user_id` → `userId`, `buyer_id` → `buyerId`, …).
 *
 * Keyed by PRISMA MODEL name (not by polyfill table name), because that is what
 * `resolveFieldName`/`filterDataKeys` receive as `modelName`. Getting this
 * wrong silently turns into “no alias found”, which is exactly how
 * `monthly_price` and the ticket `message`/`category` columns used to be
 * dropped.
 */
const FIELD_ALIASES: Record<string, Record<string, string>> = {
  // Products: the admin approval screen owns these two columns. They are added
  // additively by lib/dbBootstrap (see the Product model in schema.prisma).
  Product: { approval_status: 'approvalStatus', is_featured: 'isFeatured', image_url: 'images' },
  // The seller Plans page has always used `monthly_price`; the stored column is
  // SubscriptionPlan.price (there is no separate yearly column).
  SubscriptionPlan: { monthly_price: 'price', yearly_price: 'price' },
  // A subscription has no `price` column of its own; the amount the seller paid
  // is stored as `amount`. Aliased so ordering/filtering by price resolves
  // instead of being dropped.
  Subscription: { price: 'amount' },
  // A buyer ticket has no separate column for the body/kind of the request:
  // SupportTicket stores them in `description` and `type`.
  //
  // `ticket_number` is deliberately NOT aliased to `id`: SupportTicket.id is a
  // uuid generated by Prisma/Postgres, so writing 'TKT-…' into it would abort
  // with `invalid input syntax for type uuid`. The read mapping hands the stored
  // id back as the ticket reference instead.
  SupportTicket: { message: 'description', category: 'type' },
};

function snakeToCamel(column: string): string {
  return column.replace(/_+([a-z0-9])/g, (_match: string, char: string) => char.toUpperCase());
}

/**
 * Resolve one incoming column to the Prisma field it maps to.
 * Returns `undefined` when the table has no such column at all.
 */
function resolveFieldName(
  column: string,
  tableMapping: Record<string, string>,
  modelName: string
): string | undefined {
  if (tableMapping[column]) return tableMapping[column];

  const fields = MODEL_FIELDS[modelName];
  const alias = FIELD_ALIASES[modelName]?.[column];

  if (!fields || fields.size === 0) {
    // No DMMF (unexpected): best effort — camelCase the snake_case spelling.
    return alias || (column.includes('_') ? snakeToCamel(column) : column);
  }

  if (fields.has(column)) return column;
  const camel = alias || snakeToCamel(column);
  return fields.has(camel) ? camel : undefined;
}

/**
 * Keep only the keys that exist on the target model.
 *
 * Unknown keys used to reach Prisma verbatim and abort the whole write with
 * `Unknown argument` → HTTP 500, so approving a product, featuring a product,
 * saving a buyer profile or opening a support ticket always failed. Dropping
 * them keeps the write working, and the ignored column names are logged so the
 * gap stays visible instead of blocking the user.
 */
function filterDataKeys(
  data: Record<string, unknown>,
  table: string,
  tableMapping: Record<string, string>,
  modelName: string
): Record<string, unknown> {
  const fields = MODEL_FIELDS[modelName];
  if (!fields || fields.size === 0) return data;

  const accepted: Record<string, unknown> = {};
  const ignored: string[] = [];
  for (const [key, value] of Object.entries(data)) {
    if (fields.has(key)) {
      accepted[key] = value;
      continue;
    }
    const resolved = tableMapping[key] || FIELD_ALIASES[modelName]?.[key] || snakeToCamel(key);
    if (fields.has(resolved)) accepted[resolved] = value;
    else ignored.push(key);
  }
  if (ignored.length > 0) {
    console.warn(
      `[supabase-polyfill] ${table}: ignoring column(s) that have no database field: ${ignored.join(', ')}`
    );
  }
  return accepted;
}

/** `seller_id` coming from the browser may be a Seller row id or a user id. */
async function resolveSellerId(value: unknown): Promise<unknown> {
  const seller = await prisma.seller.findFirst({ where: { userId: String(value) } });
  return seller ? seller.id : value;
}

// Helper to convert snake_case object keys to camelCase keys for Prisma updates
function toCamelCaseKeys(obj: any): any {
  if (!obj || typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) return obj.map(toCamelCaseKeys);
  const result: any = {};
  for (const key of Object.keys(obj)) {
    const camelKey = key.replace(/_([a-z])/g, (g) => g[1].toUpperCase());
    result[camelKey] = obj[key];
  }
  return result;
}

// Auto-seed function to make the local environment immediately functional
async function ensureSeeded() {
  const planCount = await prisma.subscriptionPlan.count();
  if (planCount > 0) return;

  console.log('[AUTO-SEEDING]: Database is empty. Seeding subscription plans...');

  await prisma.$transaction(async (tx) => {
    await tx.subscriptionPlan.create({
      data: {
        name: 'Swadeshi Basic',
        description: 'List up to 50 products with standard platform fees.',
        price: 999.0,
        features: JSON.stringify(['List 50 products', 'Standard reports', 'Standard payouts']),
        durationDays: 30,
      },
    });
  });
}

// Main polyfill POST handler
export async function POST(request: Request) {
  try {
    // AUTHORIZATION — READ THIS BEFORE ADDING A TABLE.
    //
    // This route is a generic "table gateway" on behalf of the browser: the
    // caller names a table, an action, arbitrary filters and arbitrary update /
    // delete payloads, and the handler forwards them straight to Prisma. It is
    // on the public allowlist in middleware.ts, which is correct — the
    // storefront must be able to READ the public catalogue without a session.
    //
    // That made every table reachable by anyone. Confirmed in production: an
    // anonymous POST `{table:'profiles',action:'select',filters:[]}` returned all
    // 17 customer/seller profiles with names and phone numbers, and an
    // anonymous `{table:'profiles',action:'update',...}` was accepted (it also
    // exposes `delete` → `deleteMany` with caller-chosen filters).
    //
    // So access is now decided by THREE questions, in order:
    //   1. Is this table PUBLIC?          → catalog tables, read-only, no session
    //   2. Does this action WRITE?         → always requires an authenticated session
    //   3. Does the caller OWN the rows?  → the session user is forced into the
    //                                         query, so a caller cannot ask for
    //                                         someone else's order/address.
    //
    // The public set is deliberately small and is the exact set the storefront
    // reads before login. Anything not listed must not be silently public.
    const auth = await authorizePolyfillRequest(request, await body0(request));
    if (!auth.ok) return auth.response;

    // Make sure additive marketplace schema exists before client queries run
    const { ensureSchema } = await import('../../../lib/dbBootstrap');
    await ensureSchema();

    // Run auto-seed check
    await ensureSeeded();

    const body = auth.body;
    const {
      table,
      action,
      selectColumns,
      insertData,
      updateData,
      filters = [],
      orderColumn,
      orderAscending = true,
      limitCount,
      isSingle,
      isMaybeSingle,
      userId,
    } = body;

    // The caller-supplied userId must NEVER be trusted for a self-scoped table.
    // If a session exists, the session IS the identity (see enforceOwnership).
    const sessionUserId = auth.userId;

    // Handle authentication updates specifically
    //
    // SECURITY — this is a credential write. It previously took `userId` and the
    // new password straight from the request body with NO authentication, which
    // meant an anonymous caller could set the password on ANY account and then
    // log in as that user (full account takeover, including admin/executive
    // accounts). It also stored the supplied password VERBATIM: `password` is
    // NOT NULL and every other auth path writes a bcrypt/pbkdf2 hash via
    // `hashPassword()`, so this path also wrote a plaintext credential that
    // `verifyPassword()` would then reject — breaking the feature outright.
    //
    // Now: the session must exist, the target must BE the session user (staff may
    // manage another account), and the password is hashed exactly like every
    // other write in the app.
    if (table === 'profiles_auth' && action === 'update_auth') {
      const deny = NextResponse.json(
        { error: 'Unauthorized access. Please login.' },
        { status: 401 },
      );
      if (!sessionUserId) return deny;

      const targetId = String(userId || sessionUserId);
      if (targetId !== sessionUserId && !auth.isStaff) {
        return NextResponse.json(
          { error: 'Access Denied - you may only update your own account.' },
          { status: 403 },
        );
      }

      const { hashPassword } = await import('../../../lib/authUtils');

      const updatePayload: any = {};
      if (updateData?.password) {
        if (String(updateData.password).length < 6) {
          return NextResponse.json(
            { error: 'Password must be at least 6 characters long.' },
            { status: 400 },
          );
        }
        updatePayload.password = hashPassword(String(updateData.password));
      }
      if (updateData?.email) {
        updatePayload.email = String(updateData.email).toLowerCase();
      }
      if (updateData?.full_name) {
        updatePayload.fullName = String(updateData.full_name);
      }

      if (Object.keys(updatePayload).length === 0) {
        return NextResponse.json({ error: 'Nothing to update.' }, { status: 400 });
      }

      const updatedUser = await prisma.user.update({
        where: { id: targetId },
        data: updatePayload,
      });

      return NextResponse.json({
        success: true,
        user: {
          id: updatedUser.id,
          email: updatedUser.email,
          role: updatedUser.role.toLowerCase(),
          fullName: updatedUser.fullName,
          phone: updatedUser.phone,
        },
      });
    }

    // 1. Table Mappings
    if (table === 'product_categories') {
      // Categories are served from the static catalogue in this deployment: there
      // is no Category model in the schema. Reads keep working, but writes must
      // report the truth instead of answering 200 and appearing to save.
      if (action === 'select') {
        return NextResponse.json({ success: true, data: STATIC_CATEGORIES });
      }
      return NextResponse.json(
        {
          error:
            'Category editing is not available in this deployment: categories are a fixed catalogue.',
        },
        { status: 501 }
      );
    }

    // Determine Prisma delegate
    let delegate: any = null;
    let tableMapping: any = {};
    const modelName = TABLE_MODEL[table] || '';

    switch (table) {
      case 'profiles':
        delegate = prisma.user;
        tableMapping = { user_id: 'id', id: 'id', full_name: 'fullName', phone: 'phone' };
        break;
      case 'sellers':
        delegate = prisma.seller;
        tableMapping = { user_id: 'userId', id: 'id' };
        break;
      case 'products':
        delegate = prisma.product;
        tableMapping = { seller_id: 'sellerId', id: 'id' };
        break;
      case 'orders':
        delegate = prisma.order;
        tableMapping = { seller_id: 'sellerId', id: 'id' };
        break;
      case 'reviews':
        delegate = prisma.review;
        tableMapping = { id: 'id', product_id: 'productId', user_id: 'userId' };
        break;
      case 'leads':
        delegate = prisma.lead;
        tableMapping = { id: 'id' };
        break;
      case 'subscriptions':
        delegate = prisma.subscription;
        tableMapping = { id: 'id', seller_id: 'sellerId' };
        break;
      case 'subscription_plans':
        delegate = prisma.subscriptionPlan;
        tableMapping = { id: 'id' };
        break;
      case 'support_tickets':
        delegate = prisma.supportTicket;
        tableMapping = { id: 'id', user_id: 'userId' };
        break;
      case 'newsletter_subscriptions':
        delegate = prisma.newsletterSubscription;
        tableMapping = { id: 'id', email: 'email' };
        break;
      case 'contact_inquiries':
        delegate = prisma.contactInquiry;
        tableMapping = { id: 'id' };
        break;
      case 'addresses':
        delegate = prisma.address;
        tableMapping = { user_id: 'userId', id: 'id', is_default: 'isDefault', address_line1: 'addressLine1', address_line2: 'addressLine2', full_name: 'fullName' };
        break;
      default:
        return NextResponse.json({ error: `Supabase table '${table}' is not supported by the polyfill.` }, { status: 400 });
    }

    // 2. Build Where Clauses
    //
    // OWNERSHIP FIRST. For self-scoped tables the session user is pinned into the
    // query and any caller-supplied owner filter is discarded, so Customer A can
    // never read or write Customer B's orders / addresses / profile / tickets,
    // even by sending `filters: [{ column: 'user_id', value: '<other id>' }]`.
    // Staff keep the unfiltered behaviour their admin screens depend on.
    const owned = enforceOwnership(table, filters, sessionUserId, auth.isStaff);
    if (owned.denied) {
      return NextResponse.json(
        { error: 'Unauthorized access. Please login.' },
        { status: 401 },
      );
    }
    const scopedFilters = owned.filters;

    const where: any = {};
    for (const filter of scopedFilters) {
      // The browser sends Supabase column names; translate them to the Prisma
      // field (see resolveFieldName). An unknown FILTER column is deliberately
      // left untouched so Prisma reports it instead of silently widening the
      // result set.
      const col = resolveFieldName(filter.column, tableMapping, modelName) || filter.column;

      if (col.includes('.')) {
        const parts = col.split('.');
        if (parts[0] === 'products' && parts[1] === 'seller_id') {
          where.product = { sellerId: await resolveSellerId(filter.value) };
          continue;
        }
      }

      // A review has no seller of its own: the vendor store page asks for a
      // seller's reviews through the product each review belongs to.
      if (table === 'reviews' && filter.column === 'seller_id') {
        where.product = { sellerId: await resolveSellerId(filter.value) };
        continue;
      }

      let filterVal = filter.value;
      if (col === 'sellerId') {
        filterVal = await resolveSellerId(filterVal);
      }

      // Enum-ish columns are stored with whatever casing the writer used
      // (products `ACTIVE`, sellers `active`, tickets `open`…). A case-sensitive
      // compare silently returned an empty page — the buyer's Order History
      // status filter asked for 'pending' while rows say 'PENDING'. Match these
      // three columns insensitively; free-text columns stay exact.
      const caseInsensitive = col === 'status' || col === 'role' || col === 'paymentStatus';

      if (filter.operator === 'eq') {
        where[col] = caseInsensitive ? { equals: filterVal, mode: 'insensitive' } : filterVal;
      } else if (filter.operator === 'neq') {
        where[col] = { not: filterVal };
      } else if (filter.operator === 'in') {
        where[col] = { in: filterVal };
      } else if (filter.operator === 'like') {
        const val = String(filterVal).replace(/%/g, '');
        where[col] = { contains: val };
      }
    }

    // Supabase `profiles` row → Prisma `User` row, shared by insert and update.
    //  * The admin Users screen writes `status: 'active' | 'inactive'`; the User
    //    model has no `status` column, it stores the inverse boolean as isActive
    //    (the read mapping hands `status`/`is_active` back).
    //  * Roles are stored UPPER CASE ('BUYER', 'SELLER', 'ADMIN', and the
    //    corporate roles) and every API guard compares them strictly
    //    (check-admin filters role: 'ADMIN', requireRole(['FOUNDER', …])). The
    //    admin screen sends lowercase, so normalise on write — otherwise the
    //    saved user instantly fails those checks and loses access.
    const normalizeProfileData = (source: any, target: any) => {
      if (source.status !== undefined) {
        target.isActive = String(source.status).toLowerCase() !== 'inactive';
      }
      if (source.role !== undefined) {
        target.role = String(source.role).toUpperCase();
      }
      delete target.status;
      return target;
    };

    // 3. Execute CRUD Operations
    let result: any = null;

    if (action === 'select') {
      const options: any = { where };

      // Handle relations and joins requested by select query string
      if (table === 'sellers') {
        options.include = { pickupAddress: true };
      } else if (table === 'reviews') {
        options.include = { product: true, user: true };
      } else if (table === 'subscriptions') {
        options.include = { seller: true };
      } else if (table === 'orders') {
        options.include = {
          buyer: true,
          seller: true,
          items: {
            include: {
              product: true
            }
          },
          shipments: {
            include: {
              courierPartner: true
            }
          }
        };
      }

      // Ordering
      if (orderColumn) {
        const orderKey = resolveFieldName(orderColumn, tableMapping, modelName);
        if (orderKey) {
          options.orderBy = { [orderKey]: orderAscending ? 'asc' : 'desc' };
        } else {
          // e.g. `sellers.rating` / `products.image_url` are display-only and
          // have no column. Fall back to the natural order instead of failing
          // the whole read (which used to blank the page).
          console.warn(
            `[supabase-polyfill] ${table}: ignoring order by '${orderColumn}' (no matching database column)`
          );
        }
      }

      // Limit
      if (limitCount) {
        options.take = limitCount;
      }

      const rows = await delegate.findMany(options);

      // Map rows back to snake_case structure
      result = rows.map((row: any) => {
        if (table === 'profiles') {
          return {
            id: row.id,
            user_id: row.id,
            role: (row.role || 'BUYER').toLowerCase(),
            full_name: row.fullName,
            phone: row.phone,
            avatar_url: null,
            // The admin Users screen filters on `status` and toggles it; both are
            // backed by the additive User.isActive column. Rows that predate the
            // column read as active.
            status: row.isActive === false ? 'inactive' : 'active',
            is_active: row.isActive !== false,
            created_at: row.createdAt,
            updated_at: row.updatedAt,
          };
        }

        if (table === 'sellers') {
          return {
            id: row.id,
            user_id: row.userId,
            store_name: row.storeName,
            store_description: row.storeDescription,
            gst_number: row.gstNumber,
            pan_number: row.panNumber,
            bank_account_number: row.bankAccountNo,
            bank_ifsc: row.bankIfsc,
            bank_account_name: row.bankAccountName,
            store_logo_url: row.logoUrl,
            store_banner_url: row.bannerUrl,
            business_type: row.businessType,
            address: row.pickupAddress?.addressLine1 || '',
            city: row.pickupAddress?.city || row.city || '',
            state: row.pickupAddress?.state || row.state || '',
            pincode: row.pickupAddress?.pincode || row.pincode || '',
            commission_rate: row.commissionRate,
            // A row written before defaults existed must not blank the whole
            // vendor list through a null dereference.
            status: (row.status || 'PENDING').toLowerCase(),
            created_at: row.createdAt,
            updated_at: row.updatedAt,
          };
        }

        if (table === 'products') {
          // Parse image JSON to output matching product_images schema
          let productImages: any[] = [];
          if (row.images) {
            try {
              const imgs = JSON.parse(row.images);
              productImages = imgs.map((img: any) => ({
                url: img.url,
                is_primary: img.isPrimary,
              }));
            } catch (e) {
              console.warn('Failed to parse product images JSON:', e);
            }
          }
          if (productImages.length === 0) {
            productImages = [{ url: '/placeholder.jpg', is_primary: true }];
          }

          return {
            id: row.id,
            seller_id: row.sellerId,
            title: row.title,
            price: row.price,
            compare_price: row.comparePrice,
            stock: row.stock,
            category: row.category,
            short_description: row.shortDescription,
            description: row.description,
            sku: row.sku,
            barcode: row.barcode,
            status: row.status,
            tags: row.tags,
            weight: row.weight,
            dimension_length: row.dimensionLength,
            dimension_width: row.dimensionWidth,
            dimension_height: row.dimensionHeight,
            created_at: row.createdAt,
            // The admin approval screen reads these; `approvalStatus` is NULL
            // for rows that predate the column, so derive their state from
            // `status` instead of reporting everything as pending.
            approval_status:
              row.approvalStatus ?? (row.status === 'ACTIVE' ? 'APPROVED' : 'PENDING'),
            is_featured: row.isFeatured ?? false,
            // Derived display field (the model stores the images JSON array).
            image_url: productImages.find((img: any) => img.is_primary)?.url || productImages[0]?.url || null,
            product_images: productImages,
          };
        }

        if (table === 'orders') {
          let shippingAddressObj = null;
          if (row.shippingAddress) {
            try {
              shippingAddressObj = typeof row.shippingAddress === 'string'
                ? JSON.parse(row.shippingAddress)
                : row.shippingAddress;
            } catch (e) {
              console.warn('Failed to parse shipping address JSON:', e);
            }
          }

          const orderItems = (row.items || []).map((item: any) => ({
            id: item.id,
            order_id: item.orderId,
            product_id: item.productId,
            title: item.title,
            price: item.price,
            quantity: item.quantity,
            total: item.total,
            shipment_id: item.shipmentId,
            sku: item.product?.sku || 'N/A',
          }));

          const shipments = (row.shipments || []).map((ship: any) => ({
            id: ship.id,
            shipment_number: ship.shipmentNumber,
            order_id: ship.orderId,
            seller_id: ship.sellerId,
            status: (ship.status || 'PENDING').toLowerCase(),
            awb_number: ship.awbNumber,
            tracking_number: ship.trackingNumber,
            tracking_link: ship.trackingLink,
            label_url: ship.labelUrl,
            cod_amount: ship.codAmount,
            shipping_cost: ship.shippingCost,
            weight: ship.weight,
            dispatch_date: ship.dispatchDate,
            created_at: ship.createdAt,
            updated_at: ship.updatedAt,
          }));

          return {
            id: row.id,
            order_number: row.orderNumber,
            buyer_id: row.buyerId,
            buyer_name: row.buyer?.fullName || 'N/A',
            buyer_email: row.buyer?.email || 'N/A',
            buyer_phone: row.buyer?.phone || 'N/A',
            seller_id: row.sellerId,
            seller_name: row.seller?.storeName || 'N/A',
            seller_logo_url: row.seller?.logoUrl || null,
            status: (row.status || 'PENDING').toLowerCase(),
            payment_status: (row.paymentStatus || 'PENDING').toLowerCase(),
            payment_method: row.paymentMethod,
            subtotal: row.subtotal,
            discount_amount: row.discountAmount,
            shipping_amount: row.shippingAmount,
            tax_amount: row.taxAmount,
            total_amount: row.totalAmount,
            shipping_address: shippingAddressObj,
            created_at: row.createdAt,
            updated_at: row.updatedAt,
            order_items: orderItems,
            shipments: shipments,
          };
        }

        if (table === 'reviews') {
          const names = (row.user?.fullName || 'Customer Account').split(' ');
          return {
            id: row.id,
            rating: row.rating,
            comment: row.comment,
            status: row.status,
            seller_response: row.sellerResponse,
            created_at: row.createdAt,
            users: {
              first_name: names[0] || 'Customer',
              last_name: names.slice(1).join(' ') || '',
            },
            products: {
              id: row.product?.id,
              title: row.product?.title,
              seller_id: row.product?.sellerId,
            },
          };
        }

        if (table === 'subscriptions') {
          return {
            id: row.id,
            seller_id: row.sellerId,
            plan: row.planId, // plan name or ID
            billing_cycle: row.billingCycle,
            status: row.status,
            start_date: row.startDate,
            end_date: row.endDate,
            amount: row.amount,
            sellers: {
              store_name: row.seller?.storeName || 'Merchant',
            },
          };
        }

        if (table === 'subscription_plans') {
          let features: string[] = [];
          if (row.features) {
            try {
              features = JSON.parse(row.features);
            } catch (e) {
              console.warn('Failed to parse subscription plan features JSON:', e);
            }
          }
          return {
            id: row.id,
            name: row.name,
            description: row.description,
            price: row.price,
            // The seller Plans page has always read `monthly_price`.
            monthly_price: row.price,
            duration_days: row.durationDays,
            features,
          };
        }

        if (table === 'addresses') {
          return {
            id: row.id,
            user_id: row.userId,
            label: row.label,
            full_name: row.fullName || null,
            phone: row.phone || null,
            address_line1: row.addressLine1,
            address_line2: row.addressLine2 || null,
            city: row.city,
            state: row.state,
            country: row.country || 'India',
            pincode: row.pincode,
            is_default: row.isDefault,
            created_at: row.createdAt,
          };
        }

        // A buyer ticket must come back in the Supabase shape the Support screen
        // reads (ticket_number/message/category/priority/created_at) instead of
        // the raw Prisma row, which made every ticket look blank.
        if (table === 'support_tickets') {
          return {
            id: row.id,
            ticket_number: row.id,           // stored uuid doubles as the reference
            user_id: row.userId,
            order_id: row.orderId || null,
            subject: row.subject,
            message: row.description,
            category: row.type || 'general',
            // Not stored (the platform default from the original schema).
            priority: 'medium',
            assigned_to: null,
            status: (row.status || 'open').toLowerCase(),
            created_at: row.createdAt,
            updated_at: row.updatedAt,
          };
        }

        return row;
      });

      if (isSingle || isMaybeSingle) {
        result = result[0] || null;
      }
    } else if (action === 'insert') {
      const dataArray = Array.isArray(insertData) ? insertData : [insertData];
      const insertedRows = [];

      for (const rawData of dataArray) {
        const data = toCamelCaseKeys(rawData);

        // Profiles: see normalizeProfileData (status → isActive, role → UPPER CASE).
        if (table === 'profiles') normalizeProfileData(rawData, data);

        // Convert images/features JSON to string
        if (table === 'products') {
          if (rawData.images) {
            data.images = typeof rawData.images === 'string' ? rawData.images : JSON.stringify(rawData.images);
          }
          if (rawData.variants) {
            data.variants = typeof rawData.variants === 'string' ? rawData.variants : JSON.stringify(rawData.variants);
          }
          if (rawData.price) data.price = parseFloat(rawData.price);
          if (rawData.comparePrice) data.comparePrice = parseFloat(rawData.comparePrice);
          if (rawData.stock) data.stock = parseInt(rawData.stock);
          if (data.status && typeof data.status === 'string') {
            data.status = data.status.toUpperCase();
          }
          if (rawData.price) data.price = parseFloat(rawData.price);
          if (rawData.comparePrice) data.comparePrice = parseFloat(rawData.comparePrice);
          if (rawData.stock) data.stock = parseInt(rawData.stock);
        } else if (table === 'subscription_plans' && rawData.features) {
          data.features = JSON.stringify(rawData.features);
        } else if (table === 'addresses') {
          // Normalise snake_case → camelCase for Address model fields
          if (rawData.is_default !== undefined) data.isDefault = Boolean(rawData.is_default);
          if (rawData.address_line1 !== undefined) data.addressLine1 = rawData.address_line1;
          if (rawData.address_line2 !== undefined) data.addressLine2 = rawData.address_line2;
          if (rawData.full_name !== undefined) data.fullName = rawData.full_name;
          if (rawData.user_id !== undefined) data.userId = rawData.user_id;
          // Remove leftover snake_case copies so Prisma doesn't see unknown fields
          const snakeFields = ['address_line1', 'address_line2', 'full_name', 'user_id', 'is_default', 'isDefault'];
          for (const f of snakeFields) { if (f !== 'isDefault') delete (data as any)[f]; }
        }
        const newRow = await delegate.create({ data: filterDataKeys(data, table, tableMapping, modelName) });
        insertedRows.push(newRow);
      }

      result = Array.isArray(insertData) ? insertedRows : insertedRows[0];
    } else if (action === 'update') {
      const data = toCamelCaseKeys(updateData);

      // Handle nested Pickup Address updates for Sellers table
      if (table === 'sellers') {
        const addressPayload: any = {};
        let hasAddressUpdate = false;

        if (updateData.address !== undefined) {
          addressPayload.addressLine1 = updateData.address;
          hasAddressUpdate = true;
        }
        if (updateData.city !== undefined) {
          addressPayload.city = updateData.city;
          hasAddressUpdate = true;
        }
        if (updateData.state !== undefined) {
          addressPayload.state = updateData.state;
          hasAddressUpdate = true;
        }
        if (updateData.pincode !== undefined) {
          addressPayload.pincode = updateData.pincode;
          hasAddressUpdate = true;
        }

        if (hasAddressUpdate) {
          // Find matching sellers
          const targetSellers = await prisma.seller.findMany({ where, include: { user: true } });
          for (const s of targetSellers) {
            await prisma.pickupAddress.upsert({
              where: { sellerId: s.id },
              update: addressPayload,
              create: {
                sellerId: s.id,
                storeName: s.storeName,
                contactName: 'Store Contact',
                phone: s.gstNumber || '9999999999',
                email: s.user?.email || 'merchant@example.com',
                addressLine1: addressPayload.addressLine1 || '',
                city: addressPayload.city || '',
                state: addressPayload.state || '',
                pincode: addressPayload.pincode || '',
              },
            });
          }
        }

        // Clean values before Prisma update
        delete data.address;
        delete data.city;
        delete data.state;
        delete data.pincode;

        // Map camelCase fields that are custom
        if (updateData.bank_account_number !== undefined) data.bankAccountNo = updateData.bank_account_number;
        delete data.bankAccountNumber;
      }

      if (table === 'products') {
        if (updateData.images) {
          data.images = typeof updateData.images === 'string' ? updateData.images : JSON.stringify(updateData.images);
        }
        if (updateData.variants) {
          data.variants = typeof updateData.variants === 'string' ? updateData.variants : JSON.stringify(updateData.variants);
        }
        if (updateData.price) data.price = parseFloat(updateData.price);
        if (updateData.comparePrice) data.comparePrice = parseFloat(updateData.comparePrice);
        if (updateData.stock) data.stock = parseInt(updateData.stock);
      }

      if (table === 'subscription_plans' && updateData.features) {
        data.features = JSON.stringify(updateData.features);
      }

      if (table === 'addresses') {
        // Normalise snake_case → camelCase for Address model fields on update
        if (updateData.is_default !== undefined) data.isDefault = Boolean(updateData.is_default);
        if (updateData.address_line1 !== undefined) data.addressLine1 = updateData.address_line1;
        if (updateData.address_line2 !== undefined) data.addressLine2 = updateData.address_line2;
        if (updateData.full_name !== undefined) data.fullName = updateData.full_name;
        const snakeFields = ['address_line1', 'address_line2', 'full_name', 'is_default'];
        for (const f of snakeFields) delete (data as any)[f];
      }

      // Convert update parameters to match exact types
      if (data.status && typeof data.status === 'string') {
        if (table === 'sellers') {
          data.status = data.status.toUpperCase();
        } else if (table === 'products') {
          data.status = data.status.toUpperCase();
        }
      }
      // Convert update parameters to match exact types
      if (data.status && typeof data.status === 'string' && table === 'sellers') {
        data.status = data.status.toUpperCase();
      }

      // ---------------------------------------------------------------------
      // STATUS CONSISTENCY GUARD (sellers table):
      //
      // Business rule (single status model):
      //  * Account/approval status  = Seller.status  (PENDING → ACTIVE/APPROVED →
      //    REJECTED / SUSPENDED / BLOCKED)
      //  * Verification status      = Seller.verificationStatus (PENDING_VERIFICATION → VERIFIED)
      //  * Approving/activating a seller COMPLETES verification (corporate/seller-action
      //    already does this; this guard makes the invariant hold for ANY writer,
      //    including the Admin panel toggle, seeds and legacy clients).
      //
      // Without this guard, a writer that only sets `status=ACTIVE` leaves
      // `verificationStatus=PENDING_VERIFICATION`, producing contradictory rows
      // that the Corporate Approval Center shows as “ACTIVE + Unverified”.
      // ---------------------------------------------------------------------
      if (table === 'sellers') {
        if (data.verificationStatus !== undefined) {
          if (data.verificationStatus === true) data.verificationStatus = 'VERIFIED';
          else if (data.verificationStatus === false) data.verificationStatus = 'PENDING_VERIFICATION';
          else if (typeof data.verificationStatus === 'string') data.verificationStatus = data.verificationStatus.toUpperCase();
        } else if (
          typeof data.status === 'string' &&
          ['ACTIVE', 'APPROVED'].includes(data.status.toUpperCase())
        ) {
          data.verificationStatus = 'VERIFIED';
        }
      }

      // Profiles: see normalizeProfileData (status → isActive, role → UPPER CASE).
      if (table === 'profiles') normalizeProfileData(data, data);

      // Perform updates
      const updatedRows = await delegate.updateMany({
        where,
        data: filterDataKeys(data, table, tableMapping, modelName),
      });

      result = updatedRows;
    } else if (action === 'delete') {
      const deletedRows = await delegate.deleteMany({
        where,
      });
      result = deletedRows;
    }

    return NextResponse.json({ success: true, data: result });
  } catch (error: any) {
    // Never echo raw Prisma/driver internals back to the browser — Prisma error
    // objects embed connector + Postgres detail (which leaked the pooler's
    // tenant error verbatim). An outage is reported as an outage.
    const classified = classifyDbError(error);
    if (classified) {
      console.error('[supabase-polyfill] DB error:', error?.code || error?.message);
      return NextResponse.json({ error: classified }, { status: 503 });
    }
    console.error('Supabase Polyfill Router Error:', error);
    return NextResponse.json({ error: 'Data request failed. Please try again.' }, { status: 500 });
  }
}
